export const addProductContent = {
    addProductTextAr: "أضف المنتجات",
    addProductTextEn: "Add Products",

    apTitleLabelAr: "عنوان",
    apTitleLabelEn: "Title",
    apDescriptionLabelAr: "وصف",
    apDescriptionLabelEn: "Description",
    apMediaLabelAr: "الوسائط",
    apMediaLabelEn: "Media",
    apPricingLabelAr: "التسعير",
    apPricingLabelEn: "Pricing",
    apPriceLabelAr: "سعر",
    apPriceLabelEn: "Price",
    apCompareatPriceLabelAr: "قارن بالسعر",
    apCompareatPriceLabelEn: "Compare-at price",
    apCostPerItemLabelAr: "التكلفة لكل عنصر",
    apCostPerItemLabelEn: "Cost per item",
    apProfitLabelAr: "ربح",
    apProfitLabelEn: "Profit",
    apMarginLabelAr: "هامِش",
    apMarginLabelEn: "Margin",
    apChargeTaxOnThisProductTextAr: "فرض ضريبة على هذا المنتج",
    apChargeTaxOnThisProductTextEn: "Charge tax on this product",

    // Inventory
    apInventoryLabelAr: "جرد",
    apInventoryLabelEn: "Inventory",
    apQuantityLabelAr: "كمية",
    apQuantityLabelEn: "Quantity",
    apWeightLabelAr: "وزن",
    apWeightLabelEn: "Weight",
    apStockKeepingUnitTextAr: "SKU (وحدة حفظ المخزون)",
    apStockKeepingUnitTextEn: "SKU (Stock Keeping Unit)",
    apContinueSellingwhenOutofStockTextAr: "استمر في البيع عند نفاد المخزون",
    apContinueSellingwhenOutofStockTextEn: "Continue selling when out of stock",
    apUnlimitedQuantityTextAr: "كمية غير محدودة",
    apUnlimitedQuantityTextEn: "Unlimited quantity",

    // Variants
    apVariantsLabelAr: "المتغيرات",
    apVariantsLabelEn: "Variants",
    apAddVariantsBtnAr: "+ إضافة خيارات مثل الحجم أو اللون",
    apAddVariantsBtnEn: "Add options like size or color",

    // Search engine listing
    apSearchEngineListingLabelAr: "",
    apSearchEngineListingLabelEn: "Search engine listing",

    // product
    apProductCodeLabelAr: "كود المنتج",
    apProductCodeLabelEn: "Product code",
    apStatusLabelAr: "حالة",
    apStatusLabelEn: "Status",
    apSellStatusLabelAr: "حالة البيع",
    apSellStatusLabelEn: "Sell Status",
    apStatusOfWarehouseLabelAr: "حالة المستودع",
    apStatusOfWarehouseLabelEn: "Status Of Warehouse",

    // Product Organization
    apProductOrganizationTextAr: "تنظيم المنتج",
    apProductOrganizationTextEn: "Product Organization",
    apAvailabilityInWarehouseLabelAr: "التوفر في المستودع",
    apAvailabilityInWarehouseLabelEn: "Availability in warehouse",
    apLocationInWarehouseLabelAr: "الموقع في المستودع",
    apLocationInWarehouseLabelEn: "Location in warehouse",
    apProductCategoryLabelAr: "فئة المنتج",
    apProductCategoryLabelEn: "Product category",
    apProductTypeLabelAr: "نوع المنتج",
    apProductTypeLabelEn: "Product Type",
    apBrandLabelAr: "ماركة",
    apBrandLabelEn: "Brand",
    apCollectionsLabelAr: "المجموعات",
    apCollectionsLabelEn: "Collections",
    apSupportingTagsLabelAr: "العلامات الداعمة",
    apSupportingTagsLabelEn: "Supporting tags",
    apDealerLabelAr: "تاجر",
    apDealerLabelEn: "Dealer",

    apPreOrderLabelAr: "طلب مسبق",
    apPreOrderLabelEn: "Pre-Order",
    apGiftLabelAr: "هدية",
    apGiftLabelEn: "Gift",
    apReleaseDateLabelAr: "تاريخ الإصدار",
    apReleaseDateLabelEn: "Release Date",
    apDeadlineLabelAr: "موعد التسليم",
    apDeadlineLabelEn: "Deadline",
};
