export const commonContent = {
    dashboardTextAr: "لوحة الادمن",
    dashboardTextEn: "Dashboard",
    ticketsTextAr: "التذاكر",
    ticketsTextEn: "Tickets",
    ordersTextAr: "الطلبات",
    ordersTextEn: "Orders",
    marketingTextAr: "التسويق",
    marketingTextEn: "Marketing",
    catalogueTextAr: "قسم المنتجات",
    catalogueTextEn: "Catalogue",
    customersTextAr: "عملاء",
    customersTextEn: "Customers",
    settingsTextAr: "الأعدادات",
    settingsTextEn: "Settings",
    newsletterTextAr: "النشرة الإخبارية",
    newsletterTextEn: "Newsletter",
    reportsTextAr: "التقارير",
    reportsTextEn: "Reports",

    // orders
    shipmentsTextAr: "الشحنات",
    shipmentsTextEn: "Shipments",
    refundTextAr: "استرداد",
    refundTextEn: "Refund",
    lostTextAr: "ضائع",
    lostTextEn: "Lost",
    transferringAmountsTextAr: "تحويل المبالغ",
    transferringAmountsTextEn: "Transferring amounts",
    preOrderSystemTextAr: "نظام الطلب المسبق",
    preOrderSystemTextEn: "Pre-order system",
    transitOrderSystemTextAr: "نظام أمر العبور",
    transitOrderSystemTextEn: "transit-order system",
    doneListTextAr: "قائمة القيام به",
    doneListTextEn: "Done list",

    // marketing
    influencersTextAr: "المؤثرون",
    influencersTextEn: "Influencers",
    usersTextAr: "المستخدمين",
    usersTextEn: "Users",
    projectsTextAr: "المشاريع",
    projectsTextEn: "Projects",
    searchTextAr: "بحث",
    searchTextEn: "Search",
    billingPageTextEn: "صفحة الفواتير",
    billingPageTextAr: "Billing page",

    nameTextAr: "اسم",
    nameTextEn: "Name",
    emailTextAr: "بريد إلكتروني",
    emailTextEn: "Email",
    mobileTextAr: "الرقم",
    mobileTextEn: "Mobile",
    secondNumberTextAr: "الرقم الثاني",
    secondNumberTextEn: "Second Number",
    countryTextAr: "بلد",
    countryTextEn: "Country",
    cityTextAr: "مدينة",
    cityTextEn: "City",
    googleMapTextAr: "Google Map",
    googleMapTextEn: "Google Map",

    editTextAr: "تعديل",
    editTextEn: "Edit",
    discountTextAr: "خصم",
    discountTextEn: "Discount",
    applyTextAr: "تطبيق الكود",
    applyTextEn: "Apply",
    orderTextAr: "اطلب",
    orderTextEn: "Order",
    commentTextAr: "تعليق",
    commentTextEn: "Comment",

    saveTextAr: "حفظ",
    saveTextEn: "Save",
    cancleTextAr: "إالغاء",
    cancleTextEn: "Cancle",
    confirmationTextAr: "تأكيد",
    confirmationTextEn: "Confirmation",
    invoiceTextAr: "فاتورة",
    invoiceTextEn: "Invoice",
    phoneNumberTextAr: "رقم الهاتف",
    phoneNumberTextEn: "Phone Number",
    saudiArabiaTextAr: "المملكة العربية السعودية",
    saudiArabiaTextEn: "Saudi Arabia",
    postalTextAr: "البريديه",
    postalTextEn: "Postal",
    barcodeTextAr: "الباركود",
    barcodeTextEn: "Barcode",
    invoiceToTextAr: "فاتورة إلى",
    invoiceToTextEn: "Invoice to",
    addressTextAr: "العنوان",
    addressTextEn: "Address",
    subtotalTextEn: "Subtotal",
    subtotalTextAr: "المجموع الفرعي",
    cashOnDeliveryTextAr: "الدفع عند الاستلام",
    cashOnDeliveryTextEn: "Cash On Delivery",
    taxTextEn: "Tax",
    taxTextAr: "ضريبة",
    totalTextAr: "مجموع",
    totalTextEn: "Total",
};
